CREATE TABLE [dbo].[QLCards](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Icon] [nvarchar](20) NULL,
	[Title] [nvarchar](50) NULL,
	[Color] [nvarchar](10) NULL,
	[BackgroundColor] [nvarchar](10) NULL,
 CONSTRAINT [PK_QLCards] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]