CREATE TABLE [dbo].[QLIdeaDetails](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdeaDescription] [text] NOT NULL,
	[IdeaType] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_QLIdeaDetails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]