CREATE TABLE [dbo].[QLRequestTypes](
	[RequestTypeId] [int] IDENTITY(1,1) NOT NULL,
	[RequestTypeName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_QLAppName] PRIMARY KEY CLUSTERED 
(
	[RequestTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

